checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    external_code_coverage:
        timeout: 600
    php_mess_detector: true
    php_code_sniffer: false
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]